Remove date and lastmod fields from alert pages
zaproxy/zap-admin pull request #725
Opened 2022-02-24 17:27 UTC by psiinon

This will mean that we can run this script on a schedule and only get PRs if the details actually change.
Apart from the first run when all of the dates will go ;)

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

2022-02-24 17:27 UTC, thc202 approved these changes

2022-02-24 17:53 UTC, ricekot approved these changes

2022-02-24 17:55 UTC, ricekot requested changes
The workflow could be updated to run on a schedule.

2022-02-24 18:21 UTC, kingthorin approved these changes

2022-02-25 09:49 UTC, psiinon commented
Updated to run the action every Friday and to only PR if there are changes.

2022-02-25 09:53 UTC, merged